[colors]
background = '#111318'
foreground = '#e1e2e9'

cursor_bg = '#a5c8fe'
cursor_fg = '#111318'
cursor_border = '#a5c8fe'

selection_bg = '#214876'
selection_fg = '#e1e2e9'

ansi = ['#111318', '#e64c46', '#70d66e', '#dbd17b', '#5983c9', '#899ebe', '#a5c8fe', '#abb2bf']
brights = ['#5c6370', '#e05f5f', '#87e086', '#e8e097', '#b1d6ff', '#4a7da6', '#6777ae', '#ffffff']
