[colors]
background = '#1a110f'
foreground = '#f1dfdb'

cursor_bg = '#ffb4a4'
cursor_fg = '#1a110f'
cursor_border = '#ffb4a4'

selection_bg = '#733427'
selection_fg = '#f1dfdb'

ansi = ['#1a110f', '#e14984', '#9bd66e', '#dbaa7b', '#c56652', '#bf9288', '#ffb4a4', '#abb2bf']
brights = ['#5c6370', '#e05f94', '#ace086', '#e8bf97', '#ffc1af', '#bd5c5a', '#a06d57', '#ffffff']
