cursor #cdd6f4
cursor_text_color #a6adc8

foreground            #cdd6f4
background            #181825
selection_foreground  #1e1e2e
selection_background  #eba0ac
url_color             #f38ba8

color0   #181825
color1   #d46139
color2   #6ed687
color3   #ccdb7b
color4   #d15d7a
color5   #b67789
color6   #f38ba8
color7   #abb2bf
color8   #5c6370
color9   #e0805f
color10  #86e09b
color11  #dbe897
color12  #ffb7d2
color13  #b95e84
color14  #af6771
color15  #ffffff
