cursor #cdd6f4
cursor_text_color #a6adc8

foreground            #cdd6f4
background            #181825
selection_foreground  #1e1e2e
selection_background  #89b4fa
url_color             #74c7ec

color0   #181825
color1   #e74d4c
color2   #74d66e
color3   #dbce7b
color4   #358cb6
color5   #699ab1
color6   #74c7ec
color7   #abb2bf
color8   #5c6370
color9   #e05f63
color10  #8ae086
color11  #e8dd97
color12  #81e0ff
color13  #378793
color14  #5880a1
color15  #ffffff
