# Disable window decorations (top bar)
hide_window_decorations yes


# -------------------------
# Soft, low-contrast colors
# -------------------------

background #1e1e1e
foreground #c8c8c8

selection_background #3a3a3a
selection_foreground #dcdcdc

cursor #c8c8c8
cursor_text_color #1e1e1e

# Black
color0  #2a2a2a
color8  #4a4a4a

# Red
color1  #d75f5f
color9  #d75f5f

# Green
color2  #87af87
color10 #87af87

# Yellow
color3  #d7af5f
color11 #d7af5f

# Blue
color4  #87afd7
color12 #87afd7

# Magenta
color5  #af87af
color13 #af87af

# Cyan
color6  #5fafaf
color14 #5fafaf

# White
color7  #c8c8c8
color15 #e0e0e0



# Font rendering
font_family      FiraCode Nerd Font
font_size        11.5

# Reduce spacing clutter
window_padding_width 8
confirm_os_window_close 0

# Disable bell
enable_audio_bell no
visual_bell_duration 0.0
